name: ci

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ReactFullStackDemo.slnx

      - name: Test (API)
        run: dotnet test ReactFullStackDemo.slnx -c Release --no-restore

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Web Dependencies
        working-directory: src/ReactFullStackDemo.Web
        run: npm ci

      - name: Test (Web)
        working-directory: src/ReactFullStackDemo.Web
        run: npm test

      - name: Install Angular Web Dependencies
        working-directory: src/AngularFullStackDemo.Web
        run: npm ci

      - name: Test (Angular Web)
        working-directory: src/AngularFullStackDemo.Web
        run: npm test -- --watch=false --browsers=ChromeHeadless
